version: '3'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "real_estate_app_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    networks:
      - appnet
    deploy:
      restart_policy:
        condition: "on-failure"
        
  real_estate:
    restart: always
    container_name: real_estate
    build:
      context: ./real_estate/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
      #python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: 
      - postgres_db
    networks:
      - appnet
networks:
  appnet:
    driver: bridge