# Generated by Django 3.2.9 on 2021-12-02 23:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this agent', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this listing', primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True)),
                ('rooms', models.FloatField(blank=True)),
                ('bathrooms', models.FloatField(blank=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_app.agent')),
            ],
        ),
    ]
