# Generated by Django 3.2.9 on 2021-12-03 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this agent', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this agent', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_app.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this office', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this listing', primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True)),
                ('bedrooms', models.FloatField(blank=True)),
                ('bathrooms', models.FloatField(blank=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_commission', models.FloatField(blank=True)),
                ('sold', models.CharField(default='No', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_app.agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_app.customer')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='real_estate_app.office')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate_app.office'),
        ),
    ]
