# Generated by Django 3.2.9 on 2021-12-03 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_auto_20211203_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this customer', unique=True),
        ),
    ]
