# Generated by Django 3.2.9 on 2021-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
