# Generated by Django 3.2.9 on 2021-12-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0004_listing_sold_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
