# Generated by Django 3.2.9 on 2021-12-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0005_auto_20211203_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_on',
            field=models.DateTimeField(null=True),
        ),
    ]
